### PR TITLE
[WIP] implement groove_midi.Track.to_jams

### PR DESCRIPTION
**Pull request by lostanlen**

### CODE REVIEW

**Comment by kyungyunlee** [comment]
Wow looks good to me! 👍🏻

**Comment by rabitt** [comment]
@kyungyunlee - hold off on merging this PR into your branch! I'm chatting with vincent about converting this to use the built in `mirdata.jams_utils.jams_converter`!

**Comment by kyungyunlee** [comment]
@rabitt Perfect timing! I was about to merge...! I will wait :)

**Comment by rabitt** [comment]
@kyungyunlee go ahead and merge and I'm going to open yet another PR to this PR to update!

**Comment by kyungyunlee** [comment]
Done! Thanks @lostanlen @rabitt !

**Pull request merged**
